### ISSUE TITLE
Non-ascii characters in files

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#81]
When a .mo file contains a non-ascii character the merger crashes:

```
  File "mergeIdeasScript.py", line 23, in <module>
    mer.merge()
  File "/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/merger.py", line 203, in merge
    self._copy_mo_and_mos(srcFil, desFil)
  File "/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/merger.py", line 96, in _copy_mo_and_mos
    lin = string.replace(lin, ori, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 521, in replace
    return s.replace(old, new, maxreplace)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 103: ordinal not in range(128)
```

in some cases these non-ascii codes are introduced by weird characters at position zero in the file, but they can also be functional, for instance the ö in Göteborg. 

We can either
1) replace the non-ascii characters using a code snippet like:
nonAsciiString = "".join(i for i in asciiString if ord(i)<128)
2) configure the script to use UTF8:

```
import sys
reload(sys)
sys.setdefaultencoding('UTF8')
```

code from http://stackoverflow.com/questions/2276200/changing-default-encoding-of-python
?

**Comment by mwetter** [comment]
From the MSL specification: "Each Modelica file in the file-system is stored in UTF-8 format."

Hence, this needs to be supported and a added to the regression tests.

**Comment by mwetter** [comment]
@Mathadon 
I tried to reproduce it by writing a file with UTF-8 characters in the unit tests, see https://github.com/lbl-srg/BuildingsPy/commit/edf6cf953ce103e1c2c32644a4c98e714ef55dfe
Essentially, I create `test.mo` in the target and destination library, which I then merge.

However, running
```
python buildingspy/tests/test_development_merger.py
```
works fine. How can you reproduce the UnicodeDecodeError that you reported? I need to have a test in order to see how to fix it. Using `sys.setdefaultencoding('UTF8')` is not recommended as it changes the encoding for all other modules too.

**Comment by mwetter** [comment]
@Mathadon Is this still an issue or should it be closed?

**Comment by Mathadon** [comment]
I still need to look into this. I'll put it on my to do list!

**Comment by thorade** [comment]
There is UTF-8 with or without BOM:
https://en.wikipedia.org/wiki/Byte_order_mark
That is the weird character at position zero.
Some editors (e.g. Notepad++ on Windows) can tell you what encoding was used.

To get better Unicode support (especially on Windows, where utf-8 is not the default), specify the encoding explicitly when opening a file.
To be Python 2 and 3 compatible, add `from io import open`.

So, in merger.py line ~90 (and everywhere else) change from:
```python
# Read source file, store the lines and update the content of the lines
f_sou = open(source_file, 'r')
```
to
```python
from io import open
# Read source file, store the lines and update the content of the lines
f_sou = open(source_file, mode="r", encoding="utf-8")
```

http://stackoverflow.com/questions/38186847/python-line-replace-returns-unicodeencodeerror
http://stackoverflow.com/questions/30372814/modelica-encoding-problems

**Comment by thorade** [comment]
Filip, could you show me how to reproduce this error? 
Does it still occur with the latest master? 
#121 may have fixed it as a side effect.

**Comment by Mathadon** [comment]
It's hard to reproduce since I have no idea how these weird characters get into the file. When I come across another one I'll check!

**Comment by mwetter** [comment]
@thorade @Mathadon : There was a bug in `BuildingsPy` on the `master`, leading to reference results of the form u'1.0'. I committed a fix yesterday evening to the master (https://github.com/lbl-srg/BuildingsPy/commit/3d7501d308cdd8d0607f1e693c2e24eafd246b06). Maybe this is related to your problems.

**Comment by thorade** [comment]
Turns out IDEAS had some non-ASCII characters in files that wer ASCII encoded.
Solved by https://github.com/open-ideas/IDEAS/pull/682

**Comment by Mathadon** [comment]
@mwetter That's probably the reason!

**Comment by Mathadon** [comment]
@mwetter you fixed the BuildingsPy code but did you also update the annex60 reference results? I still get the same error.

**Comment by mwetter** [comment]
@Mathadon There were some 'u' in the reference results. I fixed it on the Annex 60 master. Please try again and reopen if needed.
